version: '3.3'
services:
  psql:
    image: postgres:latest
    container_name: book_service_server_psql
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_service
    volumes:
      - database-data:/var/lib/postgresql/data/

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "book-library-service-topic:1:1"
    volumes:
      - kafka:/data
    restart: on-failure

volumes:
  database-data:
  kafka: